//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EXConnect_Plugins.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum eca_FundingTypeState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("eca_fundingtype")]
	public partial class eca_FundingType : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public eca_FundingType() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "eca_fundingtype";
		
		public const string EntitySchemaName = "eca_FundingType";
		
		public const string PrimaryIdAttribute = "eca_fundingtypeid";
		
		public const string PrimaryNameAttribute = "eca_fundingtypename";
		
		public const string EntityLogicalCollectionName = "eca_fundingtypes";
		
		public const string EntitySetName = "eca_fundingtypes";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_fundingtypeid")]
		public System.Nullable<System.Guid> eca_FundingTypeId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("eca_fundingtypeid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_FundingTypeId");
				this.SetAttributeValue("eca_fundingtypeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("eca_FundingTypeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_fundingtypeid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.eca_FundingTypeId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_fundingtypename")]
		public string eca_FundingTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("eca_fundingtypename");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_FundingTypeName");
				this.SetAttributeValue("eca_fundingtypename", value);
				this.OnPropertyChanged("eca_FundingTypeName");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Status of the Funding Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<EXConnect_Plugins.Entities.eca_FundingTypeState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((EXConnect_Plugins.Entities.eca_FundingTypeState)(System.Enum.ToObject(typeof(EXConnect_Plugins.Entities.eca_FundingTypeState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Funding Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual eca_FundingType_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((eca_FundingType_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("VersionNumber");
				this.SetAttributeValue("versionnumber", value);
				this.OnPropertyChanged("VersionNumber");
			}
		}
		
		/// <summary>
		/// 1:N eca_formulationrequest_FundingType_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_formulationrequest_FundingType_eca_fundingtype")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_FormulationRequest> eca_formulationrequest_FundingType_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_FormulationRequest>("eca_formulationrequest_FundingType_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_formulationrequest_FundingType_eca_fundingtype");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_FormulationRequest>("eca_formulationrequest_FundingType_eca_fundingtype", null, value);
				this.OnPropertyChanged("eca_formulationrequest_FundingType_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// 1:N eca_fundingsource_ParentFundingType_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_fundingsource_ParentFundingType_eca_fundingtype")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_FundingSource> eca_fundingsource_ParentFundingType_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_FundingSource>("eca_fundingsource_ParentFundingType_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_fundingsource_ParentFundingType_eca_fundingtype");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_FundingSource>("eca_fundingsource_ParentFundingType_eca_fundingtype", null, value);
				this.OnPropertyChanged("eca_fundingsource_ParentFundingType_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// 1:N eca_rcade_carttransaction_FundingType_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_rcade_carttransaction_FundingType_eca_fundingtype")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_CARTTransaction> eca_rcade_carttransaction_FundingType_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTTransaction>("eca_rcade_carttransaction_FundingType_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_rcade_carttransaction_FundingType_eca_fundingtype");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTTransaction>("eca_rcade_carttransaction_FundingType_eca_fundingtype", null, value);
				this.OnPropertyChanged("eca_rcade_carttransaction_FundingType_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// 1:N eca_rcade_monthlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_rcade_monthlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_MonthlyRollupForAppAccAssocs> eca_rcade_monthlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_MonthlyRollupForAppAccAssocs>("eca_rcade_monthlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_rcade_monthlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_MonthlyRollupForAppAccAssocs>("eca_rcade_monthlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype", null, value);
				this.OnPropertyChanged("eca_rcade_monthlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// 1:N eca_rcade_yearlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_rcade_yearlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_YearlyRollupForAppAccAssocs> eca_rcade_yearlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_YearlyRollupForAppAccAssocs>("eca_rcade_yearlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_rcade_yearlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_YearlyRollupForAppAccAssocs>("eca_rcade_yearlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype", null, value);
				this.OnPropertyChanged("eca_rcade_yearlyrollupforappaccassocs_FundingTypeonRollup_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// 1:N eca_stagedbulkuploadrecords_FundingType_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_stagedbulkuploadrecords_FundingType_eca_fundingtype")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords> eca_stagedbulkuploadrecords_FundingType_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords>("eca_stagedbulkuploadrecords_FundingType_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_stagedbulkuploadrecords_FundingType_eca_fundingtype");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords>("eca_stagedbulkuploadrecords_FundingType_eca_fundingtype", null, value);
				this.OnPropertyChanged("eca_stagedbulkuploadrecords_FundingType_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_fundingtype_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_fundingtype_createdby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_fundingtype_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_fundingtype_createdby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_createdby", null, value);
				this.OnPropertyChanged("lk_eca_fundingtype_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_fundingtype_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_fundingtype_createdonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_fundingtype_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_fundingtype_createdonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_eca_fundingtype_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_fundingtype_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_fundingtype_modifiedby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_fundingtype_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_fundingtype_modifiedby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_modifiedby", null, value);
				this.OnPropertyChanged("lk_eca_fundingtype_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_fundingtype_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_fundingtype_modifiedonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_fundingtype_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_fundingtype_modifiedonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_fundingtype_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_eca_fundingtype_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 team_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_eca_fundingtype")]
		public EXConnect_Plugins.Entities.Team team_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_eca_fundingtype");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_eca_fundingtype", null, value);
				this.OnPropertyChanged("team_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// N:1 user_eca_fundingtype
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_eca_fundingtype")]
		public EXConnect_Plugins.Entities.SystemUser user_eca_fundingtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_eca_fundingtype", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_eca_fundingtype");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_eca_fundingtype", null, value);
				this.OnPropertyChanged("user_eca_fundingtype");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public eca_FundingType(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["eca_fundingtypeid"] = base.Id;
                        break;
                    case "eca_fundingtypeid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}