//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EXConnect_Plugins.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum eca_QuotaSheetRegionalDataState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("eca_quotasheetregionaldata")]
	public partial class eca_QuotaSheetRegionalData : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public eca_QuotaSheetRegionalData() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "eca_quotasheetregionaldata";
		
		public const string EntitySchemaName = "eca_QuotaSheetRegionalData";
		
		public const string PrimaryIdAttribute = "eca_quotasheetregionaldataid";
		
		public const string PrimaryNameAttribute = "eca_name";
		
		public const string EntityLogicalCollectionName = "eca_quotasheetregionaldatas";
		
		public const string EntitySetName = "eca_quotasheetregionaldatas";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingamount")]
		public Microsoft.Xrm.Sdk.Money eca_BaseFundingAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingAmount");
				this.SetAttributeValue("eca_basefundingamount", value);
				this.OnPropertyChanged("eca_BaseFundingAmount");
			}
		}
		
		/// <summary>
		/// Value of the Base Funding Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_basefundingamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_basefundingamount_Base");
				this.SetAttributeValue("eca_basefundingamount_base", value);
				this.OnPropertyChanged("eca_basefundingamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingcentrallyfundedcount")]
		public System.Nullable<int> eca_BaseFundingCentrallyFundedCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingcentrallyfundedcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingCentrallyFundedCount");
				this.SetAttributeValue("eca_basefundingcentrallyfundedcount", value);
				this.OnPropertyChanged("eca_BaseFundingCentrallyFundedCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewamount")]
		public Microsoft.Xrm.Sdk.Money eca_BaseFundingNewAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingnewamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingNewAmount");
				this.SetAttributeValue("eca_basefundingnewamount", value);
				this.OnPropertyChanged("eca_BaseFundingNewAmount");
			}
		}
		
		/// <summary>
		/// Value of the Base Funding New Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_basefundingnewamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingnewamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_basefundingnewamount_Base");
				this.SetAttributeValue("eca_basefundingnewamount_base", value);
				this.OnPropertyChanged("eca_basefundingnewamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewcount")]
		public System.Nullable<int> eca_BaseFundingNewCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingnewcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingNewCount");
				this.SetAttributeValue("eca_basefundingnewcount", value);
				this.OnPropertyChanged("eca_BaseFundingNewCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewieacount")]
		public System.Nullable<int> eca_BaseFundingNewIEACount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingnewieacount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingNewIEACount");
				this.SetAttributeValue("eca_basefundingnewieacount", value);
				this.OnPropertyChanged("eca_BaseFundingNewIEACount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewlecturecount")]
		public System.Nullable<int> eca_BaseFundingNewLectureCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingnewlecturecount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingNewLectureCount");
				this.SetAttributeValue("eca_basefundingnewlecturecount", value);
				this.OnPropertyChanged("eca_BaseFundingNewLectureCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewotheramount")]
		public Microsoft.Xrm.Sdk.Money eca_BaseFundingNewOtherAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingnewotheramount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingNewOtherAmount");
				this.SetAttributeValue("eca_basefundingnewotheramount", value);
				this.OnPropertyChanged("eca_BaseFundingNewOtherAmount");
			}
		}
		
		/// <summary>
		/// Value of the Base Funding New Other Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewotheramount_base")]
		public Microsoft.Xrm.Sdk.Money eca_basefundingnewotheramount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingnewotheramount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_basefundingnewotheramount_Base");
				this.SetAttributeValue("eca_basefundingnewotheramount_base", value);
				this.OnPropertyChanged("eca_basefundingnewotheramount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewothercount")]
		public System.Nullable<int> eca_BaseFundingNewOtherCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingnewothercount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingNewOtherCount");
				this.SetAttributeValue("eca_basefundingnewothercount", value);
				this.OnPropertyChanged("eca_BaseFundingNewOtherCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingnewresearchcount")]
		public System.Nullable<int> eca_BaseFundingNewResearchCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingnewresearchcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingNewResearchCount");
				this.SetAttributeValue("eca_basefundingnewresearchcount", value);
				this.OnPropertyChanged("eca_BaseFundingNewResearchCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingrenewalamount")]
		public Microsoft.Xrm.Sdk.Money eca_BaseFundingRenewalAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingrenewalamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingRenewalAmount");
				this.SetAttributeValue("eca_basefundingrenewalamount", value);
				this.OnPropertyChanged("eca_BaseFundingRenewalAmount");
			}
		}
		
		/// <summary>
		/// Value of the Base Funding Renewal Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingrenewalamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_basefundingrenewalamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingrenewalamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_basefundingrenewalamount_Base");
				this.SetAttributeValue("eca_basefundingrenewalamount_base", value);
				this.OnPropertyChanged("eca_basefundingrenewalamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingrenewalcount")]
		public System.Nullable<int> eca_BaseFundingRenewalCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingrenewalcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingRenewalCount");
				this.SetAttributeValue("eca_basefundingrenewalcount", value);
				this.OnPropertyChanged("eca_BaseFundingRenewalCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingrenewalotheramount")]
		public Microsoft.Xrm.Sdk.Money eca_BaseFundingRenewalOtherAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingrenewalotheramount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingRenewalOtherAmount");
				this.SetAttributeValue("eca_basefundingrenewalotheramount", value);
				this.OnPropertyChanged("eca_BaseFundingRenewalOtherAmount");
			}
		}
		
		/// <summary>
		/// Value of the Base Funding Renewal Other Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingrenewalotheramount_base")]
		public Microsoft.Xrm.Sdk.Money eca_basefundingrenewalotheramount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingrenewalotheramount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_basefundingrenewalotheramount_Base");
				this.SetAttributeValue("eca_basefundingrenewalotheramount_base", value);
				this.OnPropertyChanged("eca_basefundingrenewalotheramount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingrenewalothercount")]
		public System.Nullable<int> eca_BaseFundingRenewalOtherCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingrenewalothercount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingRenewalOtherCount");
				this.SetAttributeValue("eca_basefundingrenewalothercount", value);
				this.OnPropertyChanged("eca_BaseFundingRenewalOtherCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingsramount")]
		public Microsoft.Xrm.Sdk.Money eca_BaseFundingSRAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingsramount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingSRAmount");
				this.SetAttributeValue("eca_basefundingsramount", value);
				this.OnPropertyChanged("eca_BaseFundingSRAmount");
			}
		}
		
		/// <summary>
		/// Value of the Base Funding S/R Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingsramount_base")]
		public Microsoft.Xrm.Sdk.Money eca_basefundingsramount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_basefundingsramount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_basefundingsramount_Base");
				this.SetAttributeValue("eca_basefundingsramount_base", value);
				this.OnPropertyChanged("eca_basefundingsramount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingsrcount")]
		public System.Nullable<int> eca_BaseFundingSRCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingsrcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingSRCount");
				this.SetAttributeValue("eca_basefundingsrcount", value);
				this.OnPropertyChanged("eca_BaseFundingSRCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_basefundingsrrenewalcount")]
		public System.Nullable<int> eca_BaseFundingSRRenewalCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_basefundingsrrenewalcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BaseFundingSRRenewalCount");
				this.SetAttributeValue("eca_basefundingsrrenewalcount", value);
				this.OnPropertyChanged("eca_BaseFundingSRRenewalCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingamount")]
		public Microsoft.Xrm.Sdk.Money eca_CarryoverFundingAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_carryoverfundingamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingAmount");
				this.SetAttributeValue("eca_carryoverfundingamount", value);
				this.OnPropertyChanged("eca_CarryoverFundingAmount");
			}
		}
		
		/// <summary>
		/// Value of the Carryover Funding Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_carryoverfundingamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_carryoverfundingamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_carryoverfundingamount_Base");
				this.SetAttributeValue("eca_carryoverfundingamount_base", value);
				this.OnPropertyChanged("eca_carryoverfundingamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingnewamount")]
		public Microsoft.Xrm.Sdk.Money eca_CarryoverFundingNewAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_carryoverfundingnewamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingNewAmount");
				this.SetAttributeValue("eca_carryoverfundingnewamount", value);
				this.OnPropertyChanged("eca_CarryoverFundingNewAmount");
			}
		}
		
		/// <summary>
		/// Value of the Carryover Funding New Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingnewamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_carryoverfundingnewamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_carryoverfundingnewamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_carryoverfundingnewamount_Base");
				this.SetAttributeValue("eca_carryoverfundingnewamount_base", value);
				this.OnPropertyChanged("eca_carryoverfundingnewamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingnewcount")]
		public System.Nullable<int> eca_CarryoverFundingNewCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_carryoverfundingnewcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingNewCount");
				this.SetAttributeValue("eca_carryoverfundingnewcount", value);
				this.OnPropertyChanged("eca_CarryoverFundingNewCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingnewieacount")]
		public System.Nullable<int> eca_CarryoverFundingNewIEACount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_carryoverfundingnewieacount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingNewIEACount");
				this.SetAttributeValue("eca_carryoverfundingnewieacount", value);
				this.OnPropertyChanged("eca_CarryoverFundingNewIEACount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingnewlecturecount")]
		public System.Nullable<int> eca_CarryoverFundingNewLectureCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_carryoverfundingnewlecturecount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingNewLectureCount");
				this.SetAttributeValue("eca_carryoverfundingnewlecturecount", value);
				this.OnPropertyChanged("eca_CarryoverFundingNewLectureCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingnewresearchcount")]
		public System.Nullable<int> eca_CarryoverFundingNewResearchCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_carryoverfundingnewresearchcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingNewResearchCount");
				this.SetAttributeValue("eca_carryoverfundingnewresearchcount", value);
				this.OnPropertyChanged("eca_CarryoverFundingNewResearchCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingrenewalamount")]
		public Microsoft.Xrm.Sdk.Money eca_CarryoverFundingRenewalAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_carryoverfundingrenewalamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingRenewalAmount");
				this.SetAttributeValue("eca_carryoverfundingrenewalamount", value);
				this.OnPropertyChanged("eca_CarryoverFundingRenewalAmount");
			}
		}
		
		/// <summary>
		/// Value of the Carryover Funding Renewal Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingrenewalamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_carryoverfundingrenewalamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_carryoverfundingrenewalamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_carryoverfundingrenewalamount_Base");
				this.SetAttributeValue("eca_carryoverfundingrenewalamount_base", value);
				this.OnPropertyChanged("eca_carryoverfundingrenewalamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_carryoverfundingrenewalcount")]
		public System.Nullable<int> eca_CarryoverFundingRenewalCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_carryoverfundingrenewalcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CarryoverFundingRenewalCount");
				this.SetAttributeValue("eca_carryoverfundingrenewalcount", value);
				this.OnPropertyChanged("eca_CarryoverFundingRenewalCount");
			}
		}
		
		/// <summary>
		/// Associated CUFF Account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_cuffaccount")]
		public Microsoft.Xrm.Sdk.EntityReference eca_CUFFAccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("eca_cuffaccount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CUFFAccount");
				this.SetAttributeValue("eca_cuffaccount", value);
				this.OnPropertyChanged("eca_CUFFAccount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_grandtotaltransferamount")]
		public System.Nullable<decimal> eca_GrandTotalTransferAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("eca_grandtotaltransferamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_GrandTotalTransferAmount");
				this.SetAttributeValue("eca_grandtotaltransferamount", value);
				this.OnPropertyChanged("eca_GrandTotalTransferAmount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_name")]
		public string eca_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("eca_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_Name");
				this.SetAttributeValue("eca_name", value);
				this.OnPropertyChanged("eca_Name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2amount")]
		public Microsoft.Xrm.Sdk.Money eca_OtherFunding2Amount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfunding2amount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2Amount");
				this.SetAttributeValue("eca_otherfunding2amount", value);
				this.OnPropertyChanged("eca_OtherFunding2Amount");
			}
		}
		
		/// <summary>
		/// Value of the Other Funding 2 Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2amount_base")]
		public Microsoft.Xrm.Sdk.Money eca_otherfunding2amount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfunding2amount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_otherfunding2amount_Base");
				this.SetAttributeValue("eca_otherfunding2amount_base", value);
				this.OnPropertyChanged("eca_otherfunding2amount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2newamount")]
		public Microsoft.Xrm.Sdk.Money eca_OtherFunding2NewAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfunding2newamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2NewAmount");
				this.SetAttributeValue("eca_otherfunding2newamount", value);
				this.OnPropertyChanged("eca_OtherFunding2NewAmount");
			}
		}
		
		/// <summary>
		/// Value of the Other Funding 2 New Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2newamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_otherfunding2newamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfunding2newamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_otherfunding2newamount_Base");
				this.SetAttributeValue("eca_otherfunding2newamount_base", value);
				this.OnPropertyChanged("eca_otherfunding2newamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2newcount")]
		public System.Nullable<int> eca_OtherFunding2NewCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfunding2newcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2NewCount");
				this.SetAttributeValue("eca_otherfunding2newcount", value);
				this.OnPropertyChanged("eca_OtherFunding2NewCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2newieacount")]
		public System.Nullable<int> eca_OtherFunding2NewIEACount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfunding2newieacount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2NewIEACount");
				this.SetAttributeValue("eca_otherfunding2newieacount", value);
				this.OnPropertyChanged("eca_OtherFunding2NewIEACount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2newlecturecount")]
		public System.Nullable<int> eca_OtherFunding2NewLectureCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfunding2newlecturecount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2NewLectureCount");
				this.SetAttributeValue("eca_otherfunding2newlecturecount", value);
				this.OnPropertyChanged("eca_OtherFunding2NewLectureCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2newresearchcount")]
		public System.Nullable<int> eca_OtherFunding2NewResearchCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfunding2newresearchcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2NewResearchCount");
				this.SetAttributeValue("eca_otherfunding2newresearchcount", value);
				this.OnPropertyChanged("eca_OtherFunding2NewResearchCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2renewalamount")]
		public Microsoft.Xrm.Sdk.Money eca_OtherFunding2RenewalAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfunding2renewalamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2RenewalAmount");
				this.SetAttributeValue("eca_otherfunding2renewalamount", value);
				this.OnPropertyChanged("eca_OtherFunding2RenewalAmount");
			}
		}
		
		/// <summary>
		/// Value of the Other Funding 2 Renewal Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2renewalamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_otherfunding2renewalamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfunding2renewalamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_otherfunding2renewalamount_Base");
				this.SetAttributeValue("eca_otherfunding2renewalamount_base", value);
				this.OnPropertyChanged("eca_otherfunding2renewalamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfunding2renewalcount")]
		public System.Nullable<int> eca_OtherFunding2RenewalCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfunding2renewalcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFunding2RenewalCount");
				this.SetAttributeValue("eca_otherfunding2renewalcount", value);
				this.OnPropertyChanged("eca_OtherFunding2RenewalCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingamount")]
		public Microsoft.Xrm.Sdk.Money eca_OtherFundingAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfundingamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingAmount");
				this.SetAttributeValue("eca_otherfundingamount", value);
				this.OnPropertyChanged("eca_OtherFundingAmount");
			}
		}
		
		/// <summary>
		/// Value of the Other Funding Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_otherfundingamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfundingamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_otherfundingamount_Base");
				this.SetAttributeValue("eca_otherfundingamount_base", value);
				this.OnPropertyChanged("eca_otherfundingamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingnewamount")]
		public Microsoft.Xrm.Sdk.Money eca_OtherFundingNewAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfundingnewamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingNewAmount");
				this.SetAttributeValue("eca_otherfundingnewamount", value);
				this.OnPropertyChanged("eca_OtherFundingNewAmount");
			}
		}
		
		/// <summary>
		/// Value of the Other Funding New Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingnewamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_otherfundingnewamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfundingnewamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_otherfundingnewamount_Base");
				this.SetAttributeValue("eca_otherfundingnewamount_base", value);
				this.OnPropertyChanged("eca_otherfundingnewamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingnewcount")]
		public System.Nullable<int> eca_OtherFundingNewCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfundingnewcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingNewCount");
				this.SetAttributeValue("eca_otherfundingnewcount", value);
				this.OnPropertyChanged("eca_OtherFundingNewCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingnewieacount")]
		public System.Nullable<int> eca_OtherFundingNewIEACount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfundingnewieacount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingNewIEACount");
				this.SetAttributeValue("eca_otherfundingnewieacount", value);
				this.OnPropertyChanged("eca_OtherFundingNewIEACount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingnewlecturecount")]
		public System.Nullable<int> eca_OtherFundingNewLectureCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfundingnewlecturecount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingNewLectureCount");
				this.SetAttributeValue("eca_otherfundingnewlecturecount", value);
				this.OnPropertyChanged("eca_OtherFundingNewLectureCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingnewresearchcount")]
		public System.Nullable<int> eca_OtherFundingNewResearchCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfundingnewresearchcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingNewResearchCount");
				this.SetAttributeValue("eca_otherfundingnewresearchcount", value);
				this.OnPropertyChanged("eca_OtherFundingNewResearchCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingrenewalamount")]
		public Microsoft.Xrm.Sdk.Money eca_OtherFundingRenewalAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfundingrenewalamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingRenewalAmount");
				this.SetAttributeValue("eca_otherfundingrenewalamount", value);
				this.OnPropertyChanged("eca_OtherFundingRenewalAmount");
			}
		}
		
		/// <summary>
		/// Value of the Other Funding Renewal Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingrenewalamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_otherfundingrenewalamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_otherfundingrenewalamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_otherfundingrenewalamount_Base");
				this.SetAttributeValue("eca_otherfundingrenewalamount_base", value);
				this.OnPropertyChanged("eca_otherfundingrenewalamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_otherfundingrenewalcount")]
		public System.Nullable<int> eca_OtherFundingRenewalCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_otherfundingrenewalcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_OtherFundingRenewalCount");
				this.SetAttributeValue("eca_otherfundingrenewalcount", value);
				this.OnPropertyChanged("eca_OtherFundingRenewalCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_parentheaderrecord")]
		public Microsoft.Xrm.Sdk.EntityReference eca_ParentHeaderRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("eca_parentheaderrecord");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_ParentHeaderRecord");
				this.SetAttributeValue("eca_parentheaderrecord", value);
				this.OnPropertyChanged("eca_ParentHeaderRecord");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_quotasheetregionaldataid")]
		public System.Nullable<System.Guid> eca_QuotaSheetRegionalDataId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("eca_quotasheetregionaldataid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_QuotaSheetRegionalDataId");
				this.SetAttributeValue("eca_quotasheetregionaldataid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("eca_QuotaSheetRegionalDataId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_quotasheetregionaldataid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.eca_QuotaSheetRegionalDataId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingamount")]
		public Microsoft.Xrm.Sdk.Money eca_RecoveryFundingAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_recoveryfundingamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingAmount");
				this.SetAttributeValue("eca_recoveryfundingamount", value);
				this.OnPropertyChanged("eca_RecoveryFundingAmount");
			}
		}
		
		/// <summary>
		/// Value of the Recovery Funding Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_recoveryfundingamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_recoveryfundingamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_recoveryfundingamount_Base");
				this.SetAttributeValue("eca_recoveryfundingamount_base", value);
				this.OnPropertyChanged("eca_recoveryfundingamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingnewamount")]
		public Microsoft.Xrm.Sdk.Money eca_RecoveryFundingNewAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_recoveryfundingnewamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingNewAmount");
				this.SetAttributeValue("eca_recoveryfundingnewamount", value);
				this.OnPropertyChanged("eca_RecoveryFundingNewAmount");
			}
		}
		
		/// <summary>
		/// Value of the Recovery Funding New Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingnewamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_recoveryfundingnewamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_recoveryfundingnewamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_recoveryfundingnewamount_Base");
				this.SetAttributeValue("eca_recoveryfundingnewamount_base", value);
				this.OnPropertyChanged("eca_recoveryfundingnewamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingnewcount")]
		public System.Nullable<int> eca_RecoveryFundingNewCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_recoveryfundingnewcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingNewCount");
				this.SetAttributeValue("eca_recoveryfundingnewcount", value);
				this.OnPropertyChanged("eca_RecoveryFundingNewCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingnewieacount")]
		public System.Nullable<int> eca_RecoveryFundingNewIEACount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_recoveryfundingnewieacount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingNewIEACount");
				this.SetAttributeValue("eca_recoveryfundingnewieacount", value);
				this.OnPropertyChanged("eca_RecoveryFundingNewIEACount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingnewlecturecount")]
		public System.Nullable<int> eca_RecoveryFundingNewLectureCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_recoveryfundingnewlecturecount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingNewLectureCount");
				this.SetAttributeValue("eca_recoveryfundingnewlecturecount", value);
				this.OnPropertyChanged("eca_RecoveryFundingNewLectureCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingnewresearchcount")]
		public System.Nullable<int> eca_RecoveryFundingNewResearchCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_recoveryfundingnewresearchcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingNewResearchCount");
				this.SetAttributeValue("eca_recoveryfundingnewresearchcount", value);
				this.OnPropertyChanged("eca_RecoveryFundingNewResearchCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingrenewalamount")]
		public Microsoft.Xrm.Sdk.Money eca_RecoveryFundingRenewalAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_recoveryfundingrenewalamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingRenewalAmount");
				this.SetAttributeValue("eca_recoveryfundingrenewalamount", value);
				this.OnPropertyChanged("eca_RecoveryFundingRenewalAmount");
			}
		}
		
		/// <summary>
		/// Value of the Recovery Funding Renewal Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingrenewalamount_base")]
		public Microsoft.Xrm.Sdk.Money eca_recoveryfundingrenewalamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("eca_recoveryfundingrenewalamount_base");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_recoveryfundingrenewalamount_Base");
				this.SetAttributeValue("eca_recoveryfundingrenewalamount_base", value);
				this.OnPropertyChanged("eca_recoveryfundingrenewalamount_Base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_recoveryfundingrenewalcount")]
		public System.Nullable<int> eca_RecoveryFundingRenewalCount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_recoveryfundingrenewalcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_RecoveryFundingRenewalCount");
				this.SetAttributeValue("eca_recoveryfundingrenewalcount", value);
				this.OnPropertyChanged("eca_RecoveryFundingRenewalCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_totalcaseload")]
		public System.Nullable<int> eca_TotalCaseLoad
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_totalcaseload");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_TotalCaseLoad");
				this.SetAttributeValue("eca_totalcaseload", value);
				this.OnPropertyChanged("eca_TotalCaseLoad");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_version")]
		public System.Nullable<int> eca_Version
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("eca_version");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_Version");
				this.SetAttributeValue("eca_version", value);
				this.OnPropertyChanged("eca_Version");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ExchangeRate");
				this.SetAttributeValue("exchangerate", value);
				this.OnPropertyChanged("ExchangeRate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Status of the Quota Sheet Regional Data
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<EXConnect_Plugins.Entities.eca_QuotaSheetRegionalDataState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((EXConnect_Plugins.Entities.eca_QuotaSheetRegionalDataState)(System.Enum.ToObject(typeof(EXConnect_Plugins.Entities.eca_QuotaSheetRegionalDataState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Quota Sheet Regional Data
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual eca_QuotaSheetRegionalData_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((eca_QuotaSheetRegionalData_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("VersionNumber");
				this.SetAttributeValue("versionnumber", value);
				this.OnPropertyChanged("VersionNumber");
			}
		}
		
		/// <summary>
		/// N:1 eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_cuffaccount")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount")]
		public EXConnect_Plugins.Entities.rcade_CUFFAccount eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.rcade_CUFFAccount>("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.rcade_CUFFAccount>("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// N:1 eca_quotasheetregionaldata_ParentHeaderRecord_eca_quotasheetheader
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_parentheaderrecord")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_quotasheetregionaldata_ParentHeaderRecord_eca_quotasheetheader")]
		public EXConnect_Plugins.Entities.eca_QuotaSheetHeader eca_quotasheetregionaldata_ParentHeaderRecord_eca_quotasheetheader
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.eca_QuotaSheetHeader>("eca_quotasheetregionaldata_ParentHeaderRecord_eca_quotasheetheader", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_quotasheetregionaldata_ParentHeaderRecord_eca_quotasheetheader");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.eca_QuotaSheetHeader>("eca_quotasheetregionaldata_ParentHeaderRecord_eca_quotasheetheader", null, value);
				this.OnPropertyChanged("eca_quotasheetregionaldata_ParentHeaderRecord_eca_quotasheetheader");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_quotasheetregionaldata_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_quotasheetregionaldata_createdby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_quotasheetregionaldata_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_quotasheetregionaldata_createdby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_createdby", null, value);
				this.OnPropertyChanged("lk_eca_quotasheetregionaldata_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_quotasheetregionaldata_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_quotasheetregionaldata_createdonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_quotasheetregionaldata_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_quotasheetregionaldata_createdonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_eca_quotasheetregionaldata_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_quotasheetregionaldata_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_quotasheetregionaldata_modifiedby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_quotasheetregionaldata_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_quotasheetregionaldata_modifiedby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_modifiedby", null, value);
				this.OnPropertyChanged("lk_eca_quotasheetregionaldata_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_eca_quotasheetregionaldata_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_eca_quotasheetregionaldata_modifiedonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_eca_quotasheetregionaldata_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_eca_quotasheetregionaldata_modifiedonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_eca_quotasheetregionaldata_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_eca_quotasheetregionaldata_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 team_eca_quotasheetregionaldata
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_eca_quotasheetregionaldata")]
		public EXConnect_Plugins.Entities.Team team_eca_quotasheetregionaldata
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_eca_quotasheetregionaldata", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_eca_quotasheetregionaldata");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_eca_quotasheetregionaldata", null, value);
				this.OnPropertyChanged("team_eca_quotasheetregionaldata");
			}
		}
		
		/// <summary>
		/// N:1 user_eca_quotasheetregionaldata
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_eca_quotasheetregionaldata")]
		public EXConnect_Plugins.Entities.SystemUser user_eca_quotasheetregionaldata
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_eca_quotasheetregionaldata", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_eca_quotasheetregionaldata");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_eca_quotasheetregionaldata", null, value);
				this.OnPropertyChanged("user_eca_quotasheetregionaldata");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public eca_QuotaSheetRegionalData(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["eca_quotasheetregionaldataid"] = base.Id;
                        break;
                    case "eca_quotasheetregionaldataid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}