//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EXConnect_Plugins.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rcade_CUFFAccountState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("rcade_cuffaccount")]
	public partial class rcade_CUFFAccount : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public rcade_CUFFAccount() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "rcade_cuffaccount";
		
		public const string EntitySchemaName = "rcade_CUFFAccount";
		
		public const string PrimaryIdAttribute = "rcade_cuffaccountid";
		
		public const string PrimaryNameAttribute = "rcade_cuffaccountname";
		
		public const string EntityLogicalCollectionName = "rcade_cuffaccounts";
		
		public const string EntitySetName = "rcade_cuffaccounts";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// List of parent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr15a_parentcuffaccount")]
		public Microsoft.Xrm.Sdk.EntityReference cr15a_ParentCUFFAccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cr15a_parentcuffaccount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cr15a_ParentCUFFAccount");
				this.SetAttributeValue("cr15a_parentcuffaccount", value);
				this.OnPropertyChanged("cr15a_ParentCUFFAccount");
			}
		}
		
		/// <summary>
		/// Zero Balance Indicator
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr37c_zerobalanceindicator")]
		public System.Nullable<bool> cr37c_ZeroBalanceIndicator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cr37c_zerobalanceindicator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cr37c_ZeroBalanceIndicator");
				this.SetAttributeValue("cr37c_zerobalanceindicator", value);
				this.OnPropertyChanged("cr37c_ZeroBalanceIndicator");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountdivision")]
		public Microsoft.Xrm.Sdk.EntityReference eca_AccountDivision
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("eca_accountdivision");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_AccountDivision");
				this.SetAttributeValue("eca_accountdivision", value);
				this.OnPropertyChanged("eca_AccountDivision");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountneighborhood")]
		public Microsoft.Xrm.Sdk.EntityReference eca_AccountNeighborhood
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("eca_accountneighborhood");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_AccountNeighborhood");
				this.SetAttributeValue("eca_accountneighborhood", value);
				this.OnPropertyChanged("eca_AccountNeighborhood");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountprogram")]
		public Microsoft.Xrm.Sdk.EntityReference eca_AccountProgram
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("eca_accountprogram");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_AccountProgram");
				this.SetAttributeValue("eca_accountprogram", value);
				this.OnPropertyChanged("eca_AccountProgram");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountsubprogram")]
		public Microsoft.Xrm.Sdk.EntityReference eca_AccountSubProgram
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("eca_accountsubprogram");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_AccountSubProgram");
				this.SetAttributeValue("eca_accountsubprogram", value);
				this.OnPropertyChanged("eca_AccountSubProgram");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_budgetlevel")]
		public virtual rcade_CUFFAccount_eca_BudgetLevel? eca_BudgetLevel
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_CUFFAccount_eca_BudgetLevel?)(EntityOptionSetEnum.GetEnum(this, "eca_budgetlevel")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_BudgetLevel");
				this.SetAttributeValue("eca_budgetlevel", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("eca_BudgetLevel");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_earmarked")]
		public System.Nullable<bool> eca_Earmarked
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("eca_earmarked");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_Earmarked");
				this.SetAttributeValue("eca_earmarked", value);
				this.OnPropertyChanged("eca_Earmarked");
			}
		}
		
		/// <summary>
		/// Column that notes whether or not a cuff account is eligible to be used on an AOA. 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_eligibleforaoa")]
		public System.Nullable<bool> eca_EligibleforAOA
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("eca_eligibleforaoa");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_EligibleforAOA");
				this.SetAttributeValue("eca_eligibleforaoa", value);
				this.OnPropertyChanged("eca_EligibleforAOA");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_eligibleforspending")]
		public System.Nullable<bool> eca_EligibleforSpending
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("eca_eligibleforspending");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_EligibleforSpending");
				this.SetAttributeValue("eca_eligibleforspending", value);
				this.OnPropertyChanged("eca_EligibleforSpending");
			}
		}
		
		/// <summary>
		/// Function Code table reference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_functioncode")]
		public Microsoft.Xrm.Sdk.EntityReference eca_FunctionCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("eca_functioncode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_FunctionCode");
				this.SetAttributeValue("eca_functioncode", value);
				this.OnPropertyChanged("eca_FunctionCode");
			}
		}
		
		/// <summary>
		/// ECA's Program name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_program")]
		public string eca_Program
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("eca_program");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_Program");
				this.SetAttributeValue("eca_program", value);
				this.OnPropertyChanged("eca_Program");
			}
		}
		
		/// <summary>
		/// Sub Account name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_subaccount")]
		public string eca_SubAccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("eca_subaccount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_SubAccount");
				this.SetAttributeValue("eca_subaccount", value);
				this.OnPropertyChanged("eca_SubAccount");
			}
		}
		
		/// <summary>
		/// Name of ECA's Sub-Program
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_subprogram")]
		public string eca_SubProgram
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("eca_subprogram");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_SubProgram");
				this.SetAttributeValue("eca_subprogram", value);
				this.OnPropertyChanged("eca_SubProgram");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_cuffaccountid")]
		public System.Nullable<System.Guid> rcade_CUFFAccountId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("rcade_cuffaccountid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CUFFAccountId");
				this.SetAttributeValue("rcade_cuffaccountid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("rcade_CUFFAccountId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_cuffaccountid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.rcade_CUFFAccountId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_cuffaccountjustification")]
		public string rcade_cuffaccountjustification
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_cuffaccountjustification");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_cuffaccountjustification");
				this.SetAttributeValue("rcade_cuffaccountjustification", value);
				this.OnPropertyChanged("rcade_cuffaccountjustification");
			}
		}
		
		/// <summary>
		/// Required name field
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_cuffaccountname")]
		public string rcade_CUFFAccountName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_cuffaccountname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CUFFAccountName");
				this.SetAttributeValue("rcade_cuffaccountname", value);
				this.OnPropertyChanged("rcade_CUFFAccountName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_cuffaccounttype")]
		public virtual rcade_CUFFAccountType? rcade_CuffAccountType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_CUFFAccountType?)(EntityOptionSetEnum.GetEnum(this, "rcade_cuffaccounttype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CuffAccountType");
				this.SetAttributeValue("rcade_cuffaccounttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("rcade_CuffAccountType");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_description")]
		public string rcade_description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_description");
				this.SetAttributeValue("rcade_description", value);
				this.OnPropertyChanged("rcade_description");
			}
		}
		
		/// <summary>
		/// Previous CART's Directorate name repurposed for ECA's Neighborhood name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_directorate")]
		public string rcade_Directorate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_directorate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_Directorate");
				this.SetAttributeValue("rcade_directorate", value);
				this.OnPropertyChanged("rcade_Directorate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_directorateofficeandaccount")]
		public string rcade_DirectorateOfficeandAccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_directorateofficeandaccount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_DirectorateOfficeandAccount");
				this.SetAttributeValue("rcade_directorateofficeandaccount", value);
				this.OnPropertyChanged("rcade_DirectorateOfficeandAccount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_divisionbranch")]
		public string rcade_DivisionBranch
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_divisionbranch");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_DivisionBranch");
				this.SetAttributeValue("rcade_divisionbranch", value);
				this.OnPropertyChanged("rcade_DivisionBranch");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_dsps")]
		public string rcade_DSPS
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_dsps");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_DSPS");
				this.SetAttributeValue("rcade_dsps", value);
				this.OnPropertyChanged("rcade_DSPS");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_dspsid")]
		public System.Nullable<int> rcade_DSPSID
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("rcade_dspsid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_DSPSID");
				this.SetAttributeValue("rcade_dspsid", value);
				this.OnPropertyChanged("rcade_DSPSID");
			}
		}
		
		/// <summary>
		/// Lookup to the DSPS table to prevent typos.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_dspslookup")]
		public Microsoft.Xrm.Sdk.EntityReference rcade_DSPSLookup
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("rcade_dspslookup");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_DSPSLookup");
				this.SetAttributeValue("rcade_dspslookup", value);
				this.OnPropertyChanged("rcade_DSPSLookup");
			}
		}
		
		/// <summary>
		/// Yes/No Field on Cuff Account called EFM
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_efm")]
		public System.Nullable<bool> rcade_EFM
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("rcade_efm");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_EFM");
				this.SetAttributeValue("rcade_efm", value);
				this.OnPropertyChanged("rcade_EFM");
			}
		}
		
		/// <summary>
		/// Previous CART's Office repurposed as ECA's Division name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_office")]
		public string rcade_Office
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_office");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_Office");
				this.SetAttributeValue("rcade_office", value);
				this.OnPropertyChanged("rcade_Office");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_resourcemanagementteam")]
		public Microsoft.Xrm.Sdk.EntityReference rcade_ResourceManagementTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("rcade_resourcemanagementteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_ResourceManagementTeam");
				this.SetAttributeValue("rcade_resourcemanagementteam", value);
				this.OnPropertyChanged("rcade_ResourceManagementTeam");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_resourcemanager")]
		public Microsoft.Xrm.Sdk.EntityReference rcade_ResourceManager
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("rcade_resourcemanager");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_ResourceManager");
				this.SetAttributeValue("rcade_resourcemanager", value);
				this.OnPropertyChanged("rcade_ResourceManager");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_securitycategory")]
		public virtual rcade_SecurityCategory? rcade_SecurityCategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_SecurityCategory?)(EntityOptionSetEnum.GetEnum(this, "rcade_securitycategory")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_SecurityCategory");
				this.SetAttributeValue("rcade_securitycategory", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("rcade_SecurityCategory");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_seniorresoucemanagername")]
		public string rcade_SeniorResouceManagerName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_seniorresoucemanagername");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_SeniorResouceManagerName");
				this.SetAttributeValue("rcade_seniorresoucemanagername", value);
				this.OnPropertyChanged("rcade_SeniorResouceManagerName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_seniorrmusername")]
		public string rcade_SeniorRMUserName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_seniorrmusername");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_SeniorRMUserName");
				this.SetAttributeValue("rcade_seniorrmusername", value);
				this.OnPropertyChanged("rcade_SeniorRMUserName");
			}
		}
		
		/// <summary>
		/// Field to be updated by a web resource that will trigger the Appropriation Account Association Generation flow.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_triggerassociationflow")]
		public System.Nullable<int> rcade_triggerassociationflow
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("rcade_triggerassociationflow");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_triggerassociationflow");
				this.SetAttributeValue("rcade_triggerassociationflow", value);
				this.OnPropertyChanged("rcade_triggerassociationflow");
			}
		}
		
		/// <summary>
		/// Status of the CUFFAccount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<EXConnect_Plugins.Entities.rcade_CUFFAccountState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((EXConnect_Plugins.Entities.rcade_CUFFAccountState)(System.Enum.ToObject(typeof(EXConnect_Plugins.Entities.rcade_CUFFAccountState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the CUFFAccount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual rcade_CUFFAccount_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_CUFFAccount_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("VersionNumber");
				this.SetAttributeValue("versionnumber", value);
				this.OnPropertyChanged("VersionNumber");
			}
		}
		
		/// <summary>
		/// 1:N cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_CUFFAccount> Referencedcr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_CUFFAccount>("cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedcr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_CUFFAccount>("cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedcr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// 1:N eca_formulationrequest_Account_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_formulationrequest_Account_rcade_cuffaccount")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_FormulationRequest> eca_formulationrequest_Account_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_FormulationRequest>("eca_formulationrequest_Account_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_formulationrequest_Account_rcade_cuffaccount");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_FormulationRequest>("eca_formulationrequest_Account_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("eca_formulationrequest_Account_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// 1:N eca_frontofficequotasheet_CUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_frontofficequotasheet_CUFFAccount_rcade_cuffaccount")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_FrontOfficeQuotaSheet> eca_frontofficequotasheet_CUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_FrontOfficeQuotaSheet>("eca_frontofficequotasheet_CUFFAccount_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_frontofficequotasheet_CUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_FrontOfficeQuotaSheet>("eca_frontofficequotasheet_CUFFAccount_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("eca_frontofficequotasheet_CUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// 1:N eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_QuotaSheetRegionalData> eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_QuotaSheetRegionalData>("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_QuotaSheetRegionalData>("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("eca_quotasheetregionaldata_CUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// 1:N eca_quotasheettocuffaccount_CUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_quotasheettocuffaccount_CUFFAccount_rcade_cuffaccount")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_QuotaSheetToCUFFAccountMap> eca_quotasheettocuffaccount_CUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_QuotaSheetToCUFFAccountMap>("eca_quotasheettocuffaccount_CUFFAccount_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_quotasheettocuffaccount_CUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_QuotaSheetToCUFFAccountMap>("eca_quotasheettocuffaccount_CUFFAccount_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("eca_quotasheettocuffaccount_CUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// 1:N eca_stagedbulkuploadrecords_CUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_stagedbulkuploadrecords_CUFFAccount_rcade_cuffaccount")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords> eca_stagedbulkuploadrecords_CUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords>("eca_stagedbulkuploadrecords_CUFFAccount_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_stagedbulkuploadrecords_CUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords>("eca_stagedbulkuploadrecords_CUFFAccount_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("eca_stagedbulkuploadrecords_CUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// 1:N eca_stagedbulkuploadrecords_FromCUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_stagedbulkuploadrecords_FromCUFFAccount_rcade_cuffaccount")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords> eca_stagedbulkuploadrecords_FromCUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords>("eca_stagedbulkuploadrecords_FromCUFFAccount_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_stagedbulkuploadrecords_FromCUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.eca_StagedBulkUploadRecords>("eca_stagedbulkuploadrecords_FromCUFFAccount_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("eca_stagedbulkuploadrecords_FromCUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// 1:N rcade_CARTTransaction_fromcuffaccount_rca
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_CARTTransaction_fromcuffaccount_rca")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_CARTTransaction> rcade_CARTTransaction_fromcuffaccount_rca
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTTransaction>("rcade_CARTTransaction_fromcuffaccount_rca", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CARTTransaction_fromcuffaccount_rca");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTTransaction>("rcade_CARTTransaction_fromcuffaccount_rca", null, value);
				this.OnPropertyChanged("rcade_CARTTransaction_fromcuffaccount_rca");
			}
		}
		
		/// <summary>
		/// 1:N rcade_CARTTransaction_rcade_CUFFAccount_r
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_CARTTransaction_rcade_CUFFAccount_r")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_CARTTransaction> rcade_CARTTransaction_rcade_CUFFAccount_r
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTTransaction>("rcade_CARTTransaction_rcade_CUFFAccount_r", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CARTTransaction_rcade_CUFFAccount_r");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTTransaction>("rcade_CARTTransaction_rcade_CUFFAccount_r", null, value);
				this.OnPropertyChanged("rcade_CARTTransaction_rcade_CUFFAccount_r");
			}
		}
		
		/// <summary>
		/// 1:N rcade_MonthlyRollupForAppAccAssocs_CUFFAc
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_MonthlyRollupForAppAccAssocs_CUFFAc")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_MonthlyRollupForAppAccAssocs> rcade_MonthlyRollupForAppAccAssocs_CUFFAc
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_MonthlyRollupForAppAccAssocs>("rcade_MonthlyRollupForAppAccAssocs_CUFFAc", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_MonthlyRollupForAppAccAssocs_CUFFAc");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_MonthlyRollupForAppAccAssocs>("rcade_MonthlyRollupForAppAccAssocs_CUFFAc", null, value);
				this.OnPropertyChanged("rcade_MonthlyRollupForAppAccAssocs_CUFFAc");
			}
		}
		
		/// <summary>
		/// 1:N rcade_YearlyRollupForAppAccAssocs_CUFFAcc
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_YearlyRollupForAppAccAssocs_CUFFAcc")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_YearlyRollupForAppAccAssocs> rcade_YearlyRollupForAppAccAssocs_CUFFAcc
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_YearlyRollupForAppAccAssocs>("rcade_YearlyRollupForAppAccAssocs_CUFFAcc", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_YearlyRollupForAppAccAssocs_CUFFAcc");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_YearlyRollupForAppAccAssocs>("rcade_YearlyRollupForAppAccAssocs_CUFFAcc", null, value);
				this.OnPropertyChanged("rcade_YearlyRollupForAppAccAssocs_CUFFAcc");
			}
		}
		
		/// <summary>
		/// N:N rcade_CUFFAccount_rcade_Appropriation_rca
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_CUFFAccount_rcade_Appropriation_rca")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_Appropriation> rcade_CUFFAccount_rcade_Appropriation_rca
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_Appropriation>("rcade_CUFFAccount_rcade_Appropriation_rca", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CUFFAccount_rcade_Appropriation_rca");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_Appropriation>("rcade_CUFFAccount_rcade_Appropriation_rca", null, value);
				this.OnPropertyChanged("rcade_CUFFAccount_rcade_Appropriation_rca");
			}
		}
		
		/// <summary>
		/// N:N rcade_CUFFAccount_SystemUser_SystemUser
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_CUFFAccount_SystemUser_SystemUser")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.SystemUser> rcade_CUFFAccount_SystemUser_SystemUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.SystemUser>("rcade_CUFFAccount_SystemUser_SystemUser", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CUFFAccount_SystemUser_SystemUser");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.SystemUser>("rcade_CUFFAccount_SystemUser_SystemUser", null, value);
				this.OnPropertyChanged("rcade_CUFFAccount_SystemUser_SystemUser");
			}
		}
		
		/// <summary>
		/// N:1 cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr15a_parentcuffaccount")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public EXConnect_Plugins.Entities.rcade_CUFFAccount Referencingcr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.rcade_CUFFAccount>("cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingcr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.rcade_CUFFAccount>("cr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingcr15a_rcade_cuffaccount_ParentCUFFAccount_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// N:1 eca_CuffAccount_FunctionCode
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_functioncode")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_CuffAccount_FunctionCode")]
		public EXConnect_Plugins.Entities.eca_FunctionCode eca_CuffAccount_FunctionCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.eca_FunctionCode>("eca_CuffAccount_FunctionCode", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_CuffAccount_FunctionCode");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.eca_FunctionCode>("eca_CuffAccount_FunctionCode", null, value);
				this.OnPropertyChanged("eca_CuffAccount_FunctionCode");
			}
		}
		
		/// <summary>
		/// N:1 eca_rcade_cuffaccount_AccountDivision_eca_division
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountdivision")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_rcade_cuffaccount_AccountDivision_eca_division")]
		public EXConnect_Plugins.Entities.eca_Division eca_rcade_cuffaccount_AccountDivision_eca_division
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.eca_Division>("eca_rcade_cuffaccount_AccountDivision_eca_division", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_rcade_cuffaccount_AccountDivision_eca_division");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.eca_Division>("eca_rcade_cuffaccount_AccountDivision_eca_division", null, value);
				this.OnPropertyChanged("eca_rcade_cuffaccount_AccountDivision_eca_division");
			}
		}
		
		/// <summary>
		/// N:1 eca_rcade_cuffaccount_AccountNeighborhood_eca_neighborhood
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountneighborhood")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_rcade_cuffaccount_AccountNeighborhood_eca_neighborhood")]
		public EXConnect_Plugins.Entities.eca_Neighborhood eca_rcade_cuffaccount_AccountNeighborhood_eca_neighborhood
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.eca_Neighborhood>("eca_rcade_cuffaccount_AccountNeighborhood_eca_neighborhood", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_rcade_cuffaccount_AccountNeighborhood_eca_neighborhood");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.eca_Neighborhood>("eca_rcade_cuffaccount_AccountNeighborhood_eca_neighborhood", null, value);
				this.OnPropertyChanged("eca_rcade_cuffaccount_AccountNeighborhood_eca_neighborhood");
			}
		}
		
		/// <summary>
		/// N:1 eca_rcade_cuffaccount_AccountProgram_eca_program
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountprogram")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_rcade_cuffaccount_AccountProgram_eca_program")]
		public EXConnect_Plugins.Entities.eca_Program eca_rcade_cuffaccount_AccountProgram_eca_program
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.eca_Program>("eca_rcade_cuffaccount_AccountProgram_eca_program", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_rcade_cuffaccount_AccountProgram_eca_program");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.eca_Program>("eca_rcade_cuffaccount_AccountProgram_eca_program", null, value);
				this.OnPropertyChanged("eca_rcade_cuffaccount_AccountProgram_eca_program");
			}
		}
		
		/// <summary>
		/// N:1 eca_rcade_cuffaccount_AccountSubProgram_eca_subprogram
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("eca_accountsubprogram")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("eca_rcade_cuffaccount_AccountSubProgram_eca_subprogram")]
		public EXConnect_Plugins.Entities.eca_Subprogram eca_rcade_cuffaccount_AccountSubProgram_eca_subprogram
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.eca_Subprogram>("eca_rcade_cuffaccount_AccountSubProgram_eca_subprogram", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("eca_rcade_cuffaccount_AccountSubProgram_eca_subprogram");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.eca_Subprogram>("eca_rcade_cuffaccount_AccountSubProgram_eca_subprogram", null, value);
				this.OnPropertyChanged("eca_rcade_cuffaccount_AccountSubProgram_eca_subprogram");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_cuffaccount_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_cuffaccount_createdby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_cuffaccount_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_cuffaccount_createdby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_createdby", null, value);
				this.OnPropertyChanged("lk_rcade_cuffaccount_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_cuffaccount_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_cuffaccount_createdonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_cuffaccount_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_cuffaccount_createdonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_rcade_cuffaccount_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_cuffaccount_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_cuffaccount_modifiedby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_cuffaccount_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_cuffaccount_modifiedby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_modifiedby", null, value);
				this.OnPropertyChanged("lk_rcade_cuffaccount_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_cuffaccount_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_cuffaccount_modifiedonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_cuffaccount_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_cuffaccount_modifiedonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_cuffaccount_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_rcade_cuffaccount_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 rcade_CUFFAccount_ResourceManagementTeam_
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_resourcemanagementteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_CUFFAccount_ResourceManagementTeam_")]
		public EXConnect_Plugins.Entities.Team rcade_CUFFAccount_ResourceManagementTeam_
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.Team>("rcade_CUFFAccount_ResourceManagementTeam_", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CUFFAccount_ResourceManagementTeam_");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.Team>("rcade_CUFFAccount_ResourceManagementTeam_", null, value);
				this.OnPropertyChanged("rcade_CUFFAccount_ResourceManagementTeam_");
			}
		}
		
		/// <summary>
		/// N:1 rcade_CUFFAccount_ResourceManager_SystemU
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_resourcemanager")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_CUFFAccount_ResourceManager_SystemU")]
		public EXConnect_Plugins.Entities.SystemUser rcade_CUFFAccount_ResourceManager_SystemU
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("rcade_CUFFAccount_ResourceManager_SystemU", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_CUFFAccount_ResourceManager_SystemU");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("rcade_CUFFAccount_ResourceManager_SystemU", null, value);
				this.OnPropertyChanged("rcade_CUFFAccount_ResourceManager_SystemU");
			}
		}
		
		/// <summary>
		/// N:1 team_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_rcade_cuffaccount")]
		public EXConnect_Plugins.Entities.Team team_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_rcade_cuffaccount");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("team_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// N:1 user_rcade_cuffaccount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_rcade_cuffaccount")]
		public EXConnect_Plugins.Entities.SystemUser user_rcade_cuffaccount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_rcade_cuffaccount", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_rcade_cuffaccount");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_rcade_cuffaccount", null, value);
				this.OnPropertyChanged("user_rcade_cuffaccount");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public rcade_CUFFAccount(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["rcade_cuffaccountid"] = base.Id;
                        break;
                    case "rcade_cuffaccountid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}