//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EXConnect_Plugins.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum rcade_UserRoleAssociationsState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// The association that assigns the User to their User Role(s).
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("rcade_userroleassociations")]
	public partial class rcade_UserRoleAssociations : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public rcade_UserRoleAssociations() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "rcade_userroleassociations";
		
		public const string EntitySchemaName = "rcade_UserRoleAssociations";
		
		public const string PrimaryIdAttribute = "rcade_userroleassociationsid";
		
		public const string PrimaryNameAttribute = "rcade_name";
		
		public const string EntityLogicalCollectionName = "rcade_userroleassociationses";
		
		public const string EntitySetName = "rcade_userroleassociationses";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr37c_releasenotesstatuscart")]
		public System.Nullable<bool> cr37c_ReleaseNotesStatusCART
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cr37c_releasenotesstatuscart");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cr37c_ReleaseNotesStatusCART");
				this.SetAttributeValue("cr37c_releasenotesstatuscart", value);
				this.OnPropertyChanged("cr37c_ReleaseNotesStatusCART");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr37c_releasenotesstatusduo")]
		public System.Nullable<bool> cr37c_ReleaseNotesStatusDUO
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cr37c_releasenotesstatusduo");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cr37c_ReleaseNotesStatusDUO");
				this.SetAttributeValue("cr37c_releasenotesstatusduo", value);
				this.OnPropertyChanged("cr37c_ReleaseNotesStatusDUO");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr37c_releasenotesstatuslois")]
		public System.Nullable<bool> cr37c_ReleaseNotesStatusLOIS
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cr37c_releasenotesstatuslois");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cr37c_ReleaseNotesStatusLOIS");
				this.SetAttributeValue("cr37c_releasenotesstatuslois", value);
				this.OnPropertyChanged("cr37c_ReleaseNotesStatusLOIS");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_approvednda")]
		public virtual rcade_Boolean? rcade_ApprovedNDA
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_Boolean?)(EntityOptionSetEnum.GetEnum(this, "rcade_approvednda")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_ApprovedNDA");
				this.SetAttributeValue("rcade_approvednda", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("rcade_ApprovedNDA");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_badgenumber")]
		public string rcade_BadgeNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_badgenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_BadgeNumber");
				this.SetAttributeValue("rcade_badgenumber", value);
				this.OnPropertyChanged("rcade_BadgeNumber");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_company")]
		public string rcade_Company
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_company");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_Company");
				this.SetAttributeValue("rcade_company", value);
				this.OnPropertyChanged("rcade_Company");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_dateseenreleasenotes")]
		public System.Nullable<System.DateTime> rcade_DateSeenReleaseNotes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("rcade_dateseenreleasenotes");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_DateSeenReleaseNotes");
				this.SetAttributeValue("rcade_dateseenreleasenotes", value);
				this.OnPropertyChanged("rcade_DateSeenReleaseNotes");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_directorate")]
		public string rcade_Directorate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_directorate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_Directorate");
				this.SetAttributeValue("rcade_directorate", value);
				this.OnPropertyChanged("rcade_Directorate");
			}
		}
		
		/// <summary>
		/// This user can view all CUFF activity and create and approve AOAs.
///** Resource Management – This user can view all CUFF activity and create new Embassy Air, Miscellaneous Requests, FSI Training, Domestic Representation, and IAA, forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_financialplanning")]
		public virtual rcade_Boolean? rcade_FinancialPlanning
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_Boolean?)(EntityOptionSetEnum.GetEnum(this, "rcade_financialplanning")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_FinancialPlanning");
				this.SetAttributeValue("rcade_financialplanning", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("rcade_FinancialPlanning");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_isthirdpartycontractor")]
		public virtual rcade_Boolean? rcade_IsThirdPartyContractor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_Boolean?)(EntityOptionSetEnum.GetEnum(this, "rcade_isthirdpartycontractor")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_IsThirdPartyContractor");
				this.SetAttributeValue("rcade_isthirdpartycontractor", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("rcade_IsThirdPartyContractor");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_lastlogindate")]
		public System.Nullable<System.DateTime> rcade_LastLoginDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("rcade_lastlogindate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_LastLoginDate");
				this.SetAttributeValue("rcade_lastlogindate", value);
				this.OnPropertyChanged("rcade_LastLoginDate");
			}
		}
		
		/// <summary>
		/// Required name field
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_name")]
		public string rcade_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_Name");
				this.SetAttributeValue("rcade_name", value);
				this.OnPropertyChanged("rcade_Name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_office")]
		public string rcade_Office
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_office");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_Office");
				this.SetAttributeValue("rcade_office", value);
				this.OnPropertyChanged("rcade_Office");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_powerbisettings")]
		public virtual System.Collections.Generic.IEnumerable<rcade_PowerBISettings> rcade_powerbisettings
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<rcade_PowerBISettings>(this, "rcade_powerbisettings");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_powerbisettings");
				this.SetAttributeValue("rcade_powerbisettings", EntityOptionSetEnum.GetMultiEnum(this, "rcade_powerbisettings", value));
				this.OnPropertyChanged("rcade_powerbisettings");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_rotatingheadersettings")]
		public virtual System.Collections.Generic.IEnumerable<rcade_RotatingHeaderSettings> rcade_rotatingheadersettings
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<rcade_RotatingHeaderSettings>(this, "rcade_rotatingheadersettings");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_rotatingheadersettings");
				this.SetAttributeValue("rcade_rotatingheadersettings", EntityOptionSetEnum.GetMultiEnum(this, "rcade_rotatingheadersettings", value));
				this.OnPropertyChanged("rcade_rotatingheadersettings");
			}
		}
		
		/// <summary>
		/// Send Welcome Email Flag
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_sendwelcomeemail")]
		public System.Nullable<bool> rcade_SendWelcomeEmail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("rcade_sendwelcomeemail");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_SendWelcomeEmail");
				this.SetAttributeValue("rcade_sendwelcomeemail", value);
				this.OnPropertyChanged("rcade_SendWelcomeEmail");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_team")]
		public virtual rcade_UserTeams? rcade_team
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_UserTeams?)(EntityOptionSetEnum.GetEnum(this, "rcade_team")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_team");
				this.SetAttributeValue("rcade_team", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("rcade_team");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_title")]
		public string rcade_Title
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_title");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_Title");
				this.SetAttributeValue("rcade_title", value);
				this.OnPropertyChanged("rcade_Title");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_transactionviewsettings")]
		public virtual System.Collections.Generic.IEnumerable<rcade_TransactionViewSettings> rcade_transactionviewsettings
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<rcade_TransactionViewSettings>(this, "rcade_transactionviewsettings");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_transactionviewsettings");
				this.SetAttributeValue("rcade_transactionviewsettings", EntityOptionSetEnum.GetMultiEnum(this, "rcade_transactionviewsettings", value));
				this.OnPropertyChanged("rcade_transactionviewsettings");
			}
		}
		
		/// <summary>
		/// This will be a hidden field on the form that will be set upon the form being saved by a Webresource. This will then trigger a plugin.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_triggeruserroleastextplugin")]
		public string rcade_triggerUserRoleAsTextPlugin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_triggeruserroleastextplugin");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_triggerUserRoleAsTextPlugin");
				this.SetAttributeValue("rcade_triggeruserroleastextplugin", value);
				this.OnPropertyChanged("rcade_triggerUserRoleAsTextPlugin");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_userlookup")]
		public Microsoft.Xrm.Sdk.EntityReference rcade_UserLookup
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("rcade_userlookup");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_UserLookup");
				this.SetAttributeValue("rcade_userlookup", value);
				this.OnPropertyChanged("rcade_UserLookup");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_userroleassociationsastext")]
		public string rcade_UserRoleAssociationsAsText
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("rcade_userroleassociationsastext");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_UserRoleAssociationsAsText");
				this.SetAttributeValue("rcade_userroleassociationsastext", value);
				this.OnPropertyChanged("rcade_UserRoleAssociationsAsText");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_userroleassociationsid")]
		public System.Nullable<System.Guid> rcade_UserRoleAssociationsId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("rcade_userroleassociationsid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_UserRoleAssociationsId");
				this.SetAttributeValue("rcade_userroleassociationsid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("rcade_UserRoleAssociationsId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_userroleassociationsid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.rcade_UserRoleAssociationsId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_userroles")]
		public virtual System.Collections.Generic.IEnumerable<rcade_UserRoles> rcade_UserRoles
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<rcade_UserRoles>(this, "rcade_userroles");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_UserRoles");
				this.SetAttributeValue("rcade_userroles", EntityOptionSetEnum.GetMultiEnum(this, "rcade_userroles", value));
				this.OnPropertyChanged("rcade_UserRoles");
			}
		}
		
		/// <summary>
		/// Status of the User Role Associations 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<EXConnect_Plugins.Entities.rcade_UserRoleAssociationsState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((EXConnect_Plugins.Entities.rcade_UserRoleAssociationsState)(System.Enum.ToObject(typeof(EXConnect_Plugins.Entities.rcade_UserRoleAssociationsState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the User Role Associations 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual rcade_UserRoleAssociations_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((rcade_UserRoleAssociations_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("VersionNumber");
				this.SetAttributeValue("versionnumber", value);
				this.OnPropertyChanged("VersionNumber");
			}
		}
		
		/// <summary>
		/// N:N rcade_BackupUsers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_BackupUsers")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.SystemUser> rcade_BackupUsers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.SystemUser>("rcade_BackupUsers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_BackupUsers");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.SystemUser>("rcade_BackupUsers", null, value);
				this.OnPropertyChanged("rcade_BackupUsers");
			}
		}
		
		/// <summary>
		/// N:N rcade_rcade_userroleassociations_team
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_rcade_userroleassociations_team")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.Team> rcade_rcade_userroleassociations_team
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.Team>("rcade_rcade_userroleassociations_team", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_rcade_userroleassociations_team");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.Team>("rcade_rcade_userroleassociations_team", null, value);
				this.OnPropertyChanged("rcade_rcade_userroleassociations_team");
			}
		}
		
		/// <summary>
		/// N:N rcade_UserRoleAssociations_rcade_CARTUser
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_UserRoleAssociations_rcade_CARTUser")]
		public System.Collections.Generic.IEnumerable<EXConnect_Plugins.Entities.rcade_CARTUserRoles> rcade_UserRoleAssociations_rcade_CARTUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTUserRoles>("rcade_UserRoleAssociations_rcade_CARTUser", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_UserRoleAssociations_rcade_CARTUser");
				this.SetRelatedEntities<EXConnect_Plugins.Entities.rcade_CARTUserRoles>("rcade_UserRoleAssociations_rcade_CARTUser", null, value);
				this.OnPropertyChanged("rcade_UserRoleAssociations_rcade_CARTUser");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_userroleassociations_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_userroleassociations_createdby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_userroleassociations_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_createdby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_userroleassociations_createdby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_createdby", null, value);
				this.OnPropertyChanged("lk_rcade_userroleassociations_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_userroleassociations_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_userroleassociations_createdonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_userroleassociations_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_userroleassociations_createdonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_rcade_userroleassociations_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_userroleassociations_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_userroleassociations_modifiedby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_userroleassociations_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_userroleassociations_modifiedby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_modifiedby", null, value);
				this.OnPropertyChanged("lk_rcade_userroleassociations_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_rcade_userroleassociations_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_rcade_userroleassociations_modifiedonbehalfby")]
		public EXConnect_Plugins.Entities.SystemUser lk_rcade_userroleassociations_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_rcade_userroleassociations_modifiedonbehalfby");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("lk_rcade_userroleassociations_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_rcade_userroleassociations_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 rcade_UserRoleAssociations_UserLookup_Sys
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rcade_userlookup")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("rcade_UserRoleAssociations_UserLookup_Sys")]
		public EXConnect_Plugins.Entities.SystemUser rcade_UserRoleAssociations_UserLookup_Sys
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("rcade_UserRoleAssociations_UserLookup_Sys", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("rcade_UserRoleAssociations_UserLookup_Sys");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("rcade_UserRoleAssociations_UserLookup_Sys", null, value);
				this.OnPropertyChanged("rcade_UserRoleAssociations_UserLookup_Sys");
			}
		}
		
		/// <summary>
		/// N:1 team_rcade_userroleassociations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_rcade_userroleassociations")]
		public EXConnect_Plugins.Entities.Team team_rcade_userroleassociations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_rcade_userroleassociations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_rcade_userroleassociations");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.Team>("team_rcade_userroleassociations", null, value);
				this.OnPropertyChanged("team_rcade_userroleassociations");
			}
		}
		
		/// <summary>
		/// N:1 user_rcade_userroleassociations
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_rcade_userroleassociations")]
		public EXConnect_Plugins.Entities.SystemUser user_rcade_userroleassociations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_rcade_userroleassociations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_rcade_userroleassociations");
				this.SetRelatedEntity<EXConnect_Plugins.Entities.SystemUser>("user_rcade_userroleassociations", null, value);
				this.OnPropertyChanged("user_rcade_userroleassociations");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public rcade_UserRoleAssociations(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["rcade_userroleassociationsid"] = base.Id;
                        break;
                    case "rcade_userroleassociationsid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}