using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Xrm.Sdk;

using EXConnect_Plugins.Entities.Interfaces;

namespace EXConnect_Plugins.Entities
{
    public partial class rcade_CARTTransaction : ICARTtransactionRecord
    {
		#region Interrogation Properties
		
		public bool IsActive
		{
			get => StateCode == rcade_CARTTransactionState.Active;
		}

		public bool IsApproved
		{
			get => StatusCode == rcade_CARTTransaction_StatusCode.Approved;
		}
		public bool IsDraft
		{
			get => StatusCode == rcade_CARTTransaction_StatusCode.Draft;
		}
		public bool IsPending
		{
			get => StatusCode == rcade_CARTTransaction_StatusCode.Pending;
		}

		public bool IsAppropriationAllocation
		{
			get => eca_ECATransactionType == eca_ECATransactionTypes.AppropriationAllocation;
		}
		public bool IsAOA
		{
			get => eca_ECATransactionType == eca_ECATransactionTypes.AOA;
		}

		public bool IsCommitment 
        {
            get => eca_ECATransactionType == eca_ECATransactionTypes.Commitment;
		}

		public bool IsObligation
		{
			get => eca_ECATransactionType == eca_ECATransactionTypes.Obligation;
		}
		public bool IsProgramTransfer
		{
			get => eca_ECATransactionType == eca_ECATransactionTypes.ProgramTransfer;
		}

		public bool IsReimbursement
        {
            get => eca_FundingType.Name == "Reimbursement";
        }

		public bool IsAutoGenerateDocumentNumber
		{
			get => rcade_AutoGenerateOption == rcade_AutoGenerateOptions.Yes;
		}

		public int? StatusValue
		{
			get => (int?)StatusCode;
		}

		#endregion

		#region Data Properties

		[AttributeLogicalNameAttribute("rcade_carttransactiondesc")]
		public string Name
        {
            get => rcade_CARTTransactionDesc;

            set
            {
				rcade_CARTTransactionDesc = value;
            }
        }

		[AttributeLogicalNameAttribute("eca_allotment")]
		public EntityReference Allotment
		{
			get => eca_Allotment;
			set
			{
				eca_Allotment = value;
			}
		}

		[AttributeLogicalNameAttribute("rcade_appropriation")]
		public EntityReference Appropriation
		{
			get => rcade_Appropriation;
			set
			{
				rcade_Appropriation = value;
			}
		}

		[AttributeLogicalNameAttribute("rcade_post")]
		public EntityReference Post
		{
			get => rcade_Post;
			set
			{
				rcade_Post = value;
			}
		}

		[AttributeLogicalNameAttribute("cr15a_approver")]
		public EntityReference Approver
		{
			get => cr15a_Approver;
			set
			{
				cr15a_Approver = value;
			}
		}

		[AttributeLogicalNameAttribute("rcade_cuffaccount")]
		public EntityReference CUFFaccount
		{
			get => rcade_CUFFAccount;
			set
			{
				rcade_CUFFAccount = value;
			}
		}

		[AttributeLogicalNameAttribute("rcade_fromcuffaccount")]
		public EntityReference FromCUFFaccount
		{
			get => rcade_fromcuffaccount;
			set
			{
				rcade_fromcuffaccount = value;
			}
		}

		public EntityReference ApprovalStatus
		{
			get => rcade_StatusValue;
			set => rcade_StatusValue = value;
		}

		[AttributeLogicalNameAttribute("rcade_fiscalyear")]
		public int? FiscalYear
        {
            get => rcade_FiscalYear;
            set
            {
                rcade_FiscalYear = value;
            }
        }

		[AttributeLogicalNameAttribute("eca_fundingtype")]
		public EntityReference FundingType
		{
			get => eca_FundingType;
			set
			{
				eca_FundingType = value;
			}
		}

		[AttributeLogicalNameAttribute("eca_ecatransactiontype")]
		public string Type
		{
			get
			{
				return eca_ECATransactionType.ToString();
			}
			set
			{
				if (!string.IsNullOrEmpty(value))
				{
					eca_ECATransactionTypes type;
					if (Enum.TryParse<eca_ECATransactionTypes>(value, out type))
					{
						eca_ECATransactionType = type;
					}
				}
			}
		}

		[AttributeLogicalNameAttribute("rcade_transcode")]
		public string Code
		{
			get => rcade_TransCode.ToString();
			set
			{
				if (!string.IsNullOrEmpty(value))
				{
					rcade_transcode code;
					if (Enum.TryParse<rcade_transcode>(value, out code))
					{
						rcade_TransCode = code;
					}
				}
			}
		}

		[AttributeLogicalNameAttribute("eca_obligationtype")]
		public EntityReference ObligationType
		{
			get => eca_ObligationType;
			set => eca_ObligationType = value;
		}

		[AttributeLogicalNameAttribute("rcade_documentnumber")]
		public string DocumentNumber
		{
			get => rcade_DocumentNumber;
			set => rcade_DocumentNumber = value;
		}

		[AttributeLogicalNameAttribute("rcade_obligationnumber")]
		public string ObligationNumber
		{
			get => rcade_obligationnumber;
			set => rcade_obligationnumber = value;
		}

		[AttributeLogicalNameAttribute("rcade_comment")]
		public string Description
		{
			get => rcade_Comment;
			set => rcade_Comment = value;
		}

		[AttributeLogicalNameAttribute("rcade_prnumber")]
		public string PR_Number
		{
			get => rcade_prnumber;
			set => rcade_prnumber = value;
		}

		[AttributeLogicalNameAttribute("rcade_ibisrequestcode")]
		public string IBIS_RequestCode
		{
			get => rcade_IBISRequestCode;
			set => rcade_IBISRequestCode = value;
		}

		[AttributeLogicalNameAttribute("rcade_projectcode")]
		public string ProjectCode
		{
			get => rcade_ProjectCode;
			set => rcade_ProjectCode = value;
		}

		[AttributeLogicalNameAttribute("rcade_amount")]
		public decimal? Amount
        {
            get
            {
                if (rcade_Amount == null)
                {
                    return null;
                }
                return rcade_Amount.Value;
            }
            set
            {
                if (value != null)
                {
					rcade_Amount = new Money(value ?? 0);
				}
			}
        }

		[AttributeLogicalNameAttribute("eca_fundingsource")]
		public EntityReference FundingSource
		{
			get => eca_FundingSource;
			set => eca_FundingSource = value;
		}

		[AttributeLogicalNameAttribute("eca_budgetobjectcode")]
		public EntityReference BOC
		{
			get => eca_BudgetObjectCode;
			set => eca_BudgetObjectCode = value;
		}

		[AttributeLogicalNameAttribute("rcade_vendor")]
		public string Vendor
		{
			get => rcade_Vendor;
			set => rcade_Vendor = value;
		}

		[AttributeLogicalNameAttribute("rcade_vendorcode")]
		public string VendorCode
		{
			get => rcade_vendorcode;
			set => rcade_vendorcode = value;
		}

		[AttributeLogicalNameAttribute("statuscode")]
		public string Status
		{
			get => StatusCode.ToString();
			set
			{
				if (!string.IsNullOrEmpty(value))
				{
					rcade_CARTTransaction_StatusCode type;
					if (Enum.TryParse<rcade_CARTTransaction_StatusCode>(value, out type))
					{
						StatusCode = type;
					}
				}
			}
		}

		[AttributeLogicalNameAttribute("eca_initialstatus")]
		public string InitialStatus
		{
			get => eca_InitialStatus;
			set => eca_InitialStatus = value;
		}

		[AttributeLogicalNameAttribute("eca_parentdocument")]
		public EntityReference ParentDocument
		{
			get => eca_ParentDocument;
			set => eca_ParentDocument = value;
		}

		[AttributeLogicalNameAttribute("rcade_parentcarttransaction")]
		public EntityReference ParentCommitment
		{
			get => rcade_ParentCARTTransaction;
			set => rcade_ParentCARTTransaction = value;
		}

		[AttributeLogicalNameAttribute("rcade_autogenerateoption")]
		public string AutoGenerateDocumentNumber
		{
			get => rcade_AutoGenerateOption.ToString();
			set
			{
				rcade_AutoGenerateOptions option;
				if (Enum.TryParse <rcade_AutoGenerateOptions>(value, out option))
				{
					rcade_AutoGenerateOption = option;
				}
				else
				{
					rcade_AutoGenerateOption = null;
				}
			}
		}

		[AttributeLogicalNameAttribute("rcade_carttransaction")]
		public Entity Entity
        {
            get
            {
                return this;
            }
        }

		#endregion

		#region Public Methods

		public string GetCreditCardObligationNumber(IRepository dbService)
		{
			// Get the Credit Card record
			var ccRef = this.rcade_creditcardname;
			var ccRecord = ((EXConnect_ServiceContext)dbService.OrgServiceContext).rcade_creditcardSet
									.Where( c => c.Id == ccRef.Id && c.eca_FiscalYear == this.FiscalYear.ToString()).FirstOrDefault();
			if (ccRecord != null)
			{
				return ccRecord.rcade_Obligation_Number;
			}
			return null;
		}

		public ICARTtransactionRecord GetCombinedTransactionRecord( ICARTtransactionRecord transaction2 )
		{
			// Generate a combined transaction record fromjm "this" transaction and another one. Emphasis on "this" transaction.
			
			var combinedRecord = new rcade_CARTTransaction();

			combinedRecord.Id = this.Id;
			combinedRecord.Appropriation = (this.Appropriation != null ? this.Appropriation : transaction2.Appropriation);
			combinedRecord.CUFFaccount = (this.CUFFaccount != null ? this.CUFFaccount : transaction2.CUFFaccount);
			combinedRecord.FromCUFFaccount = (this.FromCUFFaccount != null ? this.FromCUFFaccount : transaction2.FromCUFFaccount);
			combinedRecord.FundingType = (this.FundingType != null ? this.FundingType : transaction2.FundingType);
			combinedRecord.FundingSource = (this.FundingSource != null ? this.FundingSource : transaction2.FundingSource);
			combinedRecord.FiscalYear = (this.FiscalYear != null ? this.FiscalYear : transaction2.FiscalYear);
			combinedRecord.Type = (!string.IsNullOrEmpty(this.Type) ? this.Type : transaction2.Type);
			combinedRecord.Status = (!string.IsNullOrEmpty(this.Status) ? this.Status : transaction2.Status);
			combinedRecord.InitialStatus = (!string.IsNullOrEmpty(this.InitialStatus) ? this.InitialStatus : transaction2.InitialStatus);
			combinedRecord.ObligationType = (this.ObligationType != null ? this.ObligationType : transaction2.ObligationType);
			combinedRecord.IBIS_RequestCode = (this.IBIS_RequestCode != null ? this.IBIS_RequestCode : transaction2.IBIS_RequestCode);
			combinedRecord.Amount = (this.Attributes.Contains("rcade_amount") ? this.Amount : transaction2.Amount);
			combinedRecord.Approver = (this.Attributes.Contains("cr15a_Approver") ? this.Approver : transaction2.Approver);
			combinedRecord.DocumentNumber = (this.DocumentNumber != null ? this.DocumentNumber : transaction2.DocumentNumber);
			combinedRecord.ParentDocument = (this.ParentDocument != null ? this.ParentDocument : transaction2.ParentDocument);
			combinedRecord.ParentCommitment = (this.ParentCommitment != null ? this.ParentCommitment : transaction2.ParentCommitment);
			combinedRecord.Allotment = (this.Allotment != null ? this.Allotment : transaction2.Allotment);
			combinedRecord.Description = (this.Description != null ? this.Description : transaction2.Description);

			return combinedRecord;
		}

		public void GetFiscalStringKeys( TransferDirection inOrOut, out string appropName, out string accountName, out string fundingType, out string fiscalYear, IRepository dbService )
		{
			appropName = this.Appropriation.Name;
			if (string.IsNullOrEmpty(appropName)) 
			{
				appropName = dbService.Appropriation.GetCodeFromId(this.Appropriation.Id);
			}

			var account = (inOrOut == TransferDirection.From ? this.FromCUFFaccount : this.CUFFaccount);
			accountName = account.Name;
			if (!string.IsNullOrEmpty(accountName)) 
			{
				accountName = dbService.CUFFaccount.GetRecordFromId(account.Id).Name;
			}

			fundingType = this.FundingType.Name;
			if (!string.IsNullOrEmpty(fundingType))
			{
				fundingType = dbService.FundingType.GetNameFromId(this.FundingType.Id);
			}

			fiscalYear = this.FiscalYear.ToString();

		}

		public decimal GetTotalObligatedFunds(IRepository dbService)
		{
			var obligations = 0M;

			// A commitment must be Approved to allow obligations against it
			if (!IsCommitment && !IsApproved)
			{
				return obligations;
			}

			// Determine the total of Obligations from this commitment
			var childObligations = dbService.Transaction.GetAllRecords()
										.Where(t => t.IsObligation && t.IsApproved && t.ParentCommitment != null && t.ParentCommitment?.Id == Id)
										.Sum(t => t.Amount);

			obligations = (childObligations == null ? 0M : childObligations.Value);
			
			return obligations;
			
		}

		#endregion
	}
}
